language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  matrix:
  - BUILD="test" INSTALL="conda"
  - BUILD="test" INSTALL="pip"

before_install:
  - if [[ $INSTALL == 'pip' ]]; then
       pip install scipy>=0.9;
       pip install -r requirements.txt;
    elif [[ $INSTALL == 'conda' ]]; then
       if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
       else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
       fi;
       bash ./miniconda.sh -b -p $HOME/miniconda;
       export PATH="$HOME/miniconda/bin:$PATH";
       conda config --set always_yes yes --set changeps1 no;
       conda update -q conda;
       conda info -a;
       conda env create -q;
       source activate cartographer;
    fi;

install:
  - pip install -e .

script:
  - py.test --cov-report= --cov=cartographer
  - travis-sphinx --nowarn --source=docs build

after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
      coveralls;  
      travis-sphinx deploy;
    fi;   
